Added option (-x) to use nginxcp's logs instead of the domlogs

diff --git a/functions/cP/root/Apache/banhammer b/functions/cP/root/Apache/banhammer
--- a/functions/cP/root/Apache/banhammer
+++ b/functions/cP/root/Apache/banhammer
@@ -6,15 +6,18 @@ function banhammer(){
 	local LINESTXT="5000"
 	local LOG="/root/support/logs/banned.out"
 	local RE
-	while getopts ":hal:L:" opt; do
+    local SERVLOGS="/usr/local/apache/domlogs"
+    local SERVTXT="Apache domlogs"
+	while getopts ":hl:L:ax" opt; do
 		case $opt in
 			h)
 				echo "Usage: banhammer -l [number of lines] -L [log file]"
-				echo "Find IPs in domlogs that are in RBL provide by StopForumSpam.com and ban them."
+				echo "Find IPs in Apache domlogs [default] or nginxcp logs that are in RBL provide by StopForumSpam.com and ban them."
 				echo
 				echo "    -L FILE    Sets the log file to record to. Default: /root/support/logs/banned.out"
 				echo "    -l Lines   Sets the number of lines to read from the end of each dom log. Default: 5000"
 				echo "    -a         Use the entirety of the domlogs"
+                echo "    -x         Use nginxcp logs (/var/log/nginx) instead of Apache domlogs"
 				echo "    -h         This help message"
 				return
 				;;
@@ -39,6 +42,14 @@ function banhammer(){
 				LINES="+0"
 				LINESTXT="all"
 				;;
+            x)
+                SERVLOGS="/var/log/nginx"
+                SERVTXT="nginx logs"
+                if [[ ! -d "$SERVLOGS" ]]; then
+                    echo "Error: No nginxcp logs found in $SERVLOGS" >&2
+                    return
+                fi
+                ;;
 			:)
 				echo "-$OPTARG requires an argument" >&2
 				return
@@ -56,8 +67,9 @@ function banhammer(){
 	iptables -F DROPSPAMMERS 2>/dev/null
 	iptables -X DROPSPAMMERS 2>/dev/null
 	iptables -N DROPSPAMMERS 2>/dev/null
-	echo -e "\nLooking for bot addresses in domlogs using $LINESTXT lines. This may take a while.\n"
-	comm -12 <(wget -qO- http://listed.privatesystems.net/latest/stopforumspam.com/bannedips.csv|sort) <(find /usr/local/apache/domlogs -type f 2>/dev/null|egrep -v 'bytes_log|ftpx|error\.log'|xargs tail -n $LINES|awk '{print $1}'|egrep -v '\=|[a-zA-Z]|0-9]{4}'|sort|uniq)|xargs -I % sh -c 'iptables -A DROPSPAMMERS -j DROP -s %; echo "Dropped %";'|tee -a $LOG
+	echo -e "\nLooking for bot addresses in $SERVTXT (in $SERVLOGS) using $LINESTXT lines. This may take a while.\n"
+    echo -e "Variable check: OPTIND $OPTIND OPTARG $OPTARG LINES $LINES LINESTXT $LINESTXT LOG $LOG RE $RE"
+	comm -12 <(wget -qO- http://listed.privatesystems.net/latest/stopforumspam.com/bannedips.csv|sort) <(find "$SERVLOGS" -type f 2>/dev/null|egrep -v 'bytes_log|ftpx|error\.log|*.gz'|xargs tail -n $LINES|awk '{print $1}'|egrep -v '\=|[a-zA-Z]|0-9]{4}'|sort|uniq)|xargs -I % sh -c 'iptables -A DROPSPAMMERS -j DROP -s %; echo "Dropped %";'|tee -a $LOG
 	echo "$(cat $LOG|wc -l) dropped"
 	curl -F file=@$LOG http://paste.privatesystems.net/
     
